### ISSUE TITLE
Outfit Selection Window

### ISSUE THREAD

**Issue by tysonstrange** [tysonstrange/otcv8-classicui#12]
The Next Outfit button doesn't cycle through outfits. 

![n07CMInETL](https://user-images.githubusercontent.com/7628811/175864009-34c6ee85-9c2a-4dd6-bdf2-94305bc4e3f9.gif)

The Colour Selection squares should use the select_color.png border from rawtextures folder.

![select_color](https://user-images.githubusercontent.com/7628811/175863748-e3132f2c-77e2-4d00-b050-a47ef2912b7f.png)

**Comment by tysonstrange** [comment]
The Outfit in tibia.spr file also sets a Crop size on the outfits, the window preview size is correct, but the outfit should stretch to fill the window base don the outfit crop size.

**Comment by nekiro** [comment]
https://github.com/tysonstrange/otcv8-classicui/commit/50dec7b1f0805971229676f591caf39ae24ed400
