### ISSUE TITLE
Right Click Context Menu 

### ISSUE THREAD

**Issue by tysonstrange** [tysonstrange/otcv8-classicui#2]
Right Click Context Menu is missing texture and should be using the same font used on Chat Window tabs 

![image](https://user-images.githubusercontent.com/7628811/175812075-c22b4935-333c-4550-ae74-f6804d7fce01.png)

**Comment by nekiro** [comment]
Fixed in https://github.com/tysonstrange/otcv8-classicui/commit/bb11d8118f2a4a663f6c0fc6fe15abe60fb933e1
