### ISSUE TITLE
VIP Panel

### ISSUE THREAD

**Issue by tysonstrange** [tysonstrange/otcv8-classicui#3]
VIP Names using wrong colour

Edit VIP Window is incorrect layout.

![image](https://user-images.githubusercontent.com/7628811/175812175-9a0beaa0-67fa-4e56-98f5-2b709450a115.png)

**Comment by nekiro** [comment]
https://github.com/tysonstrange/otcv8-classicui/commit/bb63fe69782b590d92f33dfec8d7c5ef1c70620c
