### ISSUE TITLE
Move Stackable Items Window

### ISSUE THREAD

**Issue by tysonstrange** [tysonstrange/otcv8-classicui#4]
Move Stackable Items window is incorrect

![image](https://user-images.githubusercontent.com/7628811/175812231-8db5b3ad-af70-4a72-9f85-314db9367e96.png)

**Comment by nekiro** [comment]
https://github.com/tysonstrange/otcv8-classicui/commit/7496cfcddc938ae3d1f18b5ae4987c21f6f9f51f
