### ISSUE TITLE
Containers 

### ISSUE THREAD

**Issue by tysonstrange** [tysonstrange/otcv8-classicui#6]
Reference Image
![image](https://user-images.githubusercontent.com/7628811/175814673-7cadf62c-050c-44ce-9274-2d2ee344d896.png)

Collapsed containers for backpacks and skills/battle/vip windows is slightly larger than it should be.

Backpack containers show lock/unlock icon in OTC, but has no locked Icon, appears as a gap.

Containers overlap the equipment window that shows Skills/Battle/VIP and Logout buttons, see also Issue #1 

Containers missing the "half tile" in the bottom left corner of the expanded windows. 

Borders should be slightly more pronounced.

**Comment by nekiro** [comment]
https://github.com/tysonstrange/otcv8-classicui/commit/2cfacb8ce73a016203fd23aa538a201f33e8b251
